# Site settings
title: Jongjin`s Blog
description: A blog about jongjinna.
baseurl: "" # the subpath of your site, e.g. /blog
url: "jongjinna.github.io" # the base hostname & protocol for your site

# User settings
username: Jongjin
user_description: 안녕하세요. 나종진입니다. <br> 성균관대학교 경영학과 졸업예정입니다.<br>
            금융 공부를 하고 있으며 현재 삼성증권에 근무하고 있습니다. <br>
            취미로 코딩을 하고 있습니다. 최근 Quantum Computing 공부를 시작했습니다. <br>
            간단하게 포트폴리오를 기록 및 정리하는 사이트입니다.
user_title: Hello, I`m Jongjin
email: njjwa1004@naver.com
twitter_username: zh5ng__zhen
github_username:  jongjinna

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
