# Site settings
title: Jongjin`s Blog
description: A blog about jongjinna.
baseurl: "" # the subpath of your site, e.g. /blog
url: "jongjinna.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jongjin Na
user_description: Hello, I`m Jongjin
user_title: Hello, I`m Jongjin
email: njjwa1004@naver.com
twitter_username: zh5ng__zhen
github_username:  jongjinna

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
